"""Phase 3 — Keyframe Image Generation.

Produces N+1 keyframe images for N clips:

  Frame 0      : Initial character reference — generated by Imagen 3 from text.
                 This is the anchor face. All subsequent frames are edits of this.

  Frames 1..N  : Expression-transition frames — generated by Gemini Flash Image.
                 Each one takes the previous frame and changes ONLY the expression
                 to match the end_emotion of that clip. This creates seamless
                 clip boundaries: last pixel of clip i = first pixel of clip i+1.

WHY TWO MODELS:
  - Imagen 3 excels at generating photorealistic humans from text. It produces
    the highest quality initial character reference.
  - Gemini Flash Image excels at image editing with an input image. It can
    change only the expression while preserving face, outfit, background exactly.
  - Using Imagen for editing is not supported (no input image parameter).
  - Using Gemini text-to-image for Frame 0 works but quality is lower than Imagen.

FALLBACK CHAIN for Frame 0:
  1. Try Imagen 3 (best quality)
  2. If Imagen fails → try Gemini Flash Image text-to-image (acceptable quality)
  3. If both fail → raise RuntimeError (cannot continue without anchor frame)

FALLBACK for Frames 1..N:
  If Gemini Image edit fails → reuse previous frame (seamless cut still works,
  just expression won't change at that boundary).
"""

import base64
import logging
from typing import Callable, Optional

from .. import config
from ..ai.imagen_client import imagen_client
from ..ai.gemini_client import gemini_image_client
from ..models import ClipPrompt, KeyFrame, ProductionBrief
from ..prompts.system_imager import build_imagen_prompt, SYSTEM_IMAGER

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def validate_keyframe_quality(
    frame: KeyFrame,
    prev_frame: Optional[KeyFrame] = None,
) -> tuple[bool, list[str]]:
    """Validate keyframe quality before presenting to user.

    Performs automated checks for common hallucination patterns:
    1. Face detection confidence (is there a clear face?)
    2. Skin smoothing detection (via edge density analysis)
    3. Frame similarity check (if prev_frame provided — only expression should change)

    Args:
        frame:      The keyframe to validate.
        prev_frame: Optional previous frame for similarity comparison.

    Returns:
        (is_valid, issues) tuple where:
        - is_valid: True if frame passes all checks
        - issues:   List of detected issue descriptions
    """
    try:
        import cv2
        import numpy as np
        import base64
    except ImportError:
        logger.warning("validate_keyframe_quality: opencv-python not installed — skipping validation")
        return True, []

    issues: list[str] = []

    # Decode base64 to numpy array
    img_bytes = base64.b64decode(frame.image_b64)
    nparr = np.frombuffer(img_bytes, np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    if img is None:
        return False, ["Failed to decode image"]

    # Check 1: Face detection
    face_cascade = cv2.CascadeClassifier(
        cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    )
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(100, 100))

    if len(faces) == 0:
        issues.append("No face detected — possible generation failure")
    elif len(faces) > 1:
        issues.append(f"Multiple faces detected ({len(faces)}) — should be single character")

    # Check 2: Skin smoothing detection via edge density
    if len(faces) == 1:
        x, y, w, h = faces[0]
        face_roi = gray[y:y + h, x:x + w]
        edges = cv2.Canny(face_roi, 50, 150)
        edge_density = np.sum(edges > 0) / (w * h)
        # Natural skin texture: edge_density > 0.15
        # Smoothed/airbrushed: edge_density < 0.10
        if edge_density < 0.10:
            issues.append(
                f"Low edge density ({edge_density:.3f}) suggests skin smoothing/airbrushing — "
                f"natural skin texture should show more detail."
            )

    # Check 3: Frame similarity (only expression should change between frames)
    if prev_frame is not None:
        try:
            from skimage.metrics import structural_similarity as ssim
        except ImportError:
            logger.warning("validate_keyframe_quality: scikit-image not installed — skipping similarity check")
            return len(issues) == 0, issues

        prev_img_bytes = base64.b64decode(prev_frame.image_b64)
        prev_nparr = np.frombuffer(prev_img_bytes, np.uint8)
        prev_img = cv2.imdecode(prev_nparr, cv2.IMREAD_COLOR)

        if prev_img is not None:
            if img.shape != prev_img.shape:
                prev_img = cv2.resize(prev_img, (img.shape[1], img.shape[0]))
            gray_curr = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            gray_prev = cv2.cvtColor(prev_img, cv2.COLOR_BGR2GRAY)
            similarity, _ = ssim(gray_curr, gray_prev, full=True)

            # Transition frames should be 85-98% similar (only expression changes)
            if similarity < 0.85:
                issues.append(
                    f"Low similarity to previous frame ({similarity:.2%}) suggests face drift or major changes. "
                    f"Only expression should change, not face structure/outfit/background."
                )
            elif similarity > 0.98:
                issues.append(
                    f"Very high similarity to previous frame ({similarity:.2%}) suggests expression may not have changed."
                )

    return len(issues) == 0, issues


def generate_keyframes(
    brief: ProductionBrief,
    clips: list[ClipPrompt],
    on_keyframe: Optional[Callable[[KeyFrame, int], None]] = None,
) -> list[KeyFrame]:
    """Generate N+1 keyframe JPEG images for a video job.

    Args:
        brief:        Validated ProductionBrief (character spec + locked background).
        clips:        Verified ClipPrompt list from Phase 2 (length = N).
        on_keyframe:  Optional callback called after each frame is generated.
                      Signature: (frame: KeyFrame, total: int) -> None

    Returns:
        list[KeyFrame] of length N+1, all with image_b64 populated.

    Raises:
        RuntimeError: If Frame 0 cannot be generated by any method.
    """
    keyframes: list[KeyFrame] = []
    total = len(clips) + 1

    # ── Frame 0: Character reference ──────────────────────────────────────
    logger.info("Phase 3: generating Frame 0 (character reference)")
    frame_0 = _generate_reference_frame(brief, clips)

    is_valid, issues = validate_keyframe_quality(frame_0, prev_frame=None)
    if not is_valid:
        logger.warning(
            "Phase 3: Frame 0 quality issues detected:\n%s\nProceeding, flagging for review.",
            "\n".join(f"  - {issue}" for issue in issues),
        )
        frame_0.validation_issues = issues

    keyframes.append(frame_0)
    logger.info("Phase 3: Frame 0 ready (%d b64 chars)", len(frame_0.image_b64))
    if on_keyframe:
        on_keyframe(frame_0, total)

    # ── Frames 1..N: Expression transition frames ─────────────────────────
    for i, clip in enumerate(clips):
        frame_index = i + 1
        logger.info(
            "Phase 3: generating Frame %d (end of Clip %d: %s)",
            frame_index, clip.clip_number, clip.end_emotion[:60],
        )
        next_frame = _generate_transition_frame(
            prev_frame=keyframes[i],
            frame_index=frame_index,
            target_emotion=clip.end_emotion,
            brief=brief,
            clip=clip,
        )

        is_valid, issues = validate_keyframe_quality(next_frame, prev_frame=keyframes[i])
        if not is_valid:
            logger.warning(
                "Phase 3: Frame %d quality issues detected:\n%s\nProceeding, flagging for review.",
                frame_index,
                "\n".join(f"  - {issue}" for issue in issues),
            )
            next_frame.validation_issues = issues

        keyframes.append(next_frame)
        if on_keyframe:
            on_keyframe(next_frame, total)

    logger.info("Phase 3 complete — %d keyframes generated", len(keyframes))
    return keyframes


def regenerate_single_keyframe(
    frame_index: int,
    prev_keyframe: KeyFrame,
    target_emotion: str,
    brief: ProductionBrief,
    clip: Optional[ClipPrompt] = None,
    custom_prompt: Optional[str] = None,
) -> KeyFrame:
    """Regenerate one keyframe (called from /regen-image endpoint).

    Args:
        frame_index:    0 = regenerate the character reference via Imagen.
                        >0 = regenerate expression edit via Gemini Image.
        prev_keyframe:  The preceding keyframe (ignored when frame_index == 0).
        target_emotion: Desired end expression.
        brief:          ProductionBrief (character spec + background).
        clip:           Corresponding ClipPrompt (used for description label).
        custom_prompt:  Optional extra instructions from the user for this regen.

    Returns:
        New KeyFrame with updated image_b64.
    """
    if frame_index == 0:
        return _generate_reference_frame(brief, clips=[], custom_prompt=custom_prompt)

    if clip is None:
        raise ValueError(f"clip must be provided for frame_index={frame_index}")

    return _generate_transition_frame(
        prev_frame=prev_keyframe,
        frame_index=frame_index,
        target_emotion=target_emotion,
        brief=brief,
        clip=clip,
        custom_prompt=custom_prompt,
    )


# ---------------------------------------------------------------------------
# Frame 0 — Imagen 3 (with Gemini fallback)
# ---------------------------------------------------------------------------

def _generate_reference_frame(
    brief: ProductionBrief,
    clips: list[ClipPrompt],
    custom_prompt: Optional[str] = None,
) -> KeyFrame:
    """Generate Frame 0 — the initial character anchor image."""
    char = brief.character
    accessories_str = ", ".join(char.accessories) if char.accessories else "none"
    marks_str = ", ".join(char.distinguishing_marks) if char.distinguishing_marks else "none"

    # Derive opening emotion from Phase 2 clip prompts (verified, final) when available.
    # Fall back to Phase 1 brief.clips if Phase 2 prompts weren't passed.
    if clips:
        # scene_summary is a one-sentence description of clip 1's emotional beat —
        # derived from the verified Phase 2 prompt, not the raw script analysis.
        first_emotional_state = (
            clips[0].scene_summary
            or clips[0].end_emotion
            or "neutral, attentive"
        )
        emotion_source = "Phase 2 clip prompt"
    else:
        first_emotional_state = (
            brief.clips[0].emotional_state if brief.clips else "neutral, attentive"
        )
        emotion_source = "Phase 1 brief"

    logger.info(
        "Phase 3: Frame 0 opening emotion (%s): %s",
        emotion_source, first_emotional_state[:80],
    )

    # Build physical baseline description for Imagen
    physical_baseline = (
        f"age {char.age}, {char.skin_tone} skin (hex {char.skin_hex}), "
        f"{char.face_shape} face. {char.hair}. "
        f"Accessories: {accessories_str}. "
        f"Distinguishing marks: {marks_str}"
    )

    # Use parameterised builder — respects gender (woman/man/person)
    prompt = build_imagen_prompt(
        physical_baseline=physical_baseline,
        outfit=char.outfit,
        gender=char.gender,
        opening_emotion=first_emotional_state,
        locked_background=brief.locked_background,
    )

    # Append user's custom feedback if provided
    if custom_prompt:
        prompt += f"\n\nUSER FEEDBACK FOR THIS REGEN: {custom_prompt}"

    image_b64: str | None = None

    # ── Attempt 1: Imagen 3 ───────────────────────────────────────────────
    try:
        image_bytes = imagen_client.generate_character_image(prompt)
        image_b64 = base64.b64encode(image_bytes).decode("utf-8")
        logger.info("Phase 3: Frame 0 generated via Imagen 3")
    except RuntimeError as exc:
        logger.warning(
            "Phase 3: Imagen 3 failed — '%s'. Trying Gemini Image fallback.", exc
        )

    # ── Attempt 2: Gemini Flash Image (text-to-image) ─────────────────────
    if image_b64 is None:
        image_b64 = gemini_image_client.generate_from_text(prompt)
        if image_b64:
            logger.info("Phase 3: Frame 0 generated via Gemini Image fallback")
        else:
            logger.error("Phase 3: Both Imagen 3 and Gemini Image fallback failed")

    # ── Hard fail if both attempts failed ─────────────────────────────────
    if image_b64 is None:
        raise RuntimeError(
            "Frame 0 generation failed: both Imagen 4 and Gemini Image returned no image.\n"
            "Check:\n"
            "  1. IMAGEN_MODEL in .env = 'imagen-4.0-generate-001' (no 'models/' prefix)\n"
            "  2. GEMINI_IMAGE_MODEL in .env = 'gemini-2.5-flash-image'\n"
            "  3. GOOGLE_API_KEY has access to both models\n"
            "  4. Prompt does not contain blocked terms (run with DEBUG logging to see sanitized prompt)"
        )

    return KeyFrame(
        index=0,
        image_b64=image_b64,
        mime_type="image/jpeg",
        description=f"Initial character reference — {first_emotional_state}",
        approved=False,
    )


# ---------------------------------------------------------------------------
# Frames 1..N — Gemini Flash Image expression edits
# ---------------------------------------------------------------------------

def _generate_transition_frame(
    prev_frame: KeyFrame,
    frame_index: int,
    target_emotion: str,
    brief: ProductionBrief,
    clip: ClipPrompt,
    custom_prompt: Optional[str] = None,
) -> KeyFrame:
    """Generate a transition frame by editing the previous frame's expression."""
    char = brief.character
    accessories_str = ", ".join(char.accessories) if char.accessories else "none"
    marks_str = ", ".join(char.distinguishing_marks) if char.distinguishing_marks else "none"

    custom_section = f"\n\nUSER FEEDBACK FOR THIS REGEN: {custom_prompt}" if custom_prompt else ""

    # Build the full instruction for the image edit
    instruction = (
        f"{SYSTEM_IMAGER}\n\n"
        f"TARGET EXPRESSION: {target_emotion}\n\n"
        f"KEEP IDENTICAL:\n"
        f"  Skin hex: {char.skin_hex}\n"
        f"  Hair: {char.hair}\n"
        f"  Outfit: {char.outfit}\n"
        f"  Accessories: {accessories_str}\n"
        f"  Distinguishing marks: {marks_str}\n"
        f"  Background: {brief.locked_background[:300]}\n"
        f"  Camera: TIGHT MCU chin to mid-chest, eye-level, static\n"
        f"  Output: 9:16 portrait, photorealistic, no text overlays"
        f"{custom_section}"
    )

    result_b64 = gemini_image_client.edit_expression(
        image_b64=prev_frame.image_b64,
        instruction=instruction,
    )

    if result_b64 is None:
        # Fallback: reuse previous frame — the cut is still seamless,
        # just the expression at that boundary won't change.
        logger.warning(
            "Phase 3: Gemini Image returned no image for Frame %d "
            "(Clip %d end-emotion: %s) — reusing previous frame as fallback",
            frame_index, clip.clip_number, target_emotion[:60],
        )
        result_b64 = prev_frame.image_b64

    return KeyFrame(
        index=frame_index,
        image_b64=result_b64,
        mime_type="image/jpeg",
        description=f"Clip {clip.clip_number} end-frame — {target_emotion[:80]}",
        approved=False,
    )