"""Phase 3 — Keyframe Image Generation.

Produces N+1 keyframe images for N clips:

  Frame 0      : Initial character reference — generated by Imagen 3 from text.
                 This is the anchor face. All subsequent frames are edits of this.

  Frames 1..N  : Expression-transition frames — generated by Gemini Flash Image.
                 Each one takes the previous frame and changes ONLY the expression
                 to match the end_emotion of that clip. This creates seamless
                 clip boundaries: last pixel of clip i = first pixel of clip i+1.

WHY TWO MODELS:
  - Imagen 3 excels at generating photorealistic humans from text. It produces
    the highest quality initial character reference.
  - Gemini Flash Image excels at image editing with an input image. It can
    change only the expression while preserving face, outfit, background exactly.
  - Using Imagen for editing is not supported (no input image parameter).
  - Using Gemini text-to-image for Frame 0 works but quality is lower than Imagen.

FALLBACK CHAIN for Frame 0:
  1. Try Imagen 3 (best quality)
  2. If Imagen fails → try Gemini Flash Image text-to-image (acceptable quality)
  3. If both fail → raise RuntimeError (cannot continue without anchor frame)

FALLBACK for Frames 1..N:
  If Gemini Image edit fails → reuse previous frame (seamless cut still works,
  just expression won't change at that boundary).
"""

import base64
import logging
from typing import Callable, Optional

from .. import config
from ..ai.imagen_client import imagen_client
from ..ai.gemini_client import gemini_image_client
from ..models import ClipPrompt, KeyFrame, ProductionBrief
from ..prompts.system_imager import IMAGEN_PROMPT_TEMPLATE, SYSTEM_IMAGER

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_keyframes(
    brief: ProductionBrief,
    clips: list[ClipPrompt],
    on_keyframe: Optional[Callable[[KeyFrame, int], None]] = None,
) -> list[KeyFrame]:
    """Generate N+1 keyframe JPEG images for a video job.

    Args:
        brief:        Validated ProductionBrief (character spec + locked background).
        clips:        Verified ClipPrompt list from Phase 2 (length = N).
        on_keyframe:  Optional callback called after each frame is generated.
                      Signature: (frame: KeyFrame, total: int) -> None

    Returns:
        list[KeyFrame] of length N+1, all with image_b64 populated.

    Raises:
        RuntimeError: If Frame 0 cannot be generated by any method.
    """
    keyframes: list[KeyFrame] = []
    total = len(clips) + 1

    # ── Frame 0: Character reference ──────────────────────────────────────
    logger.info("Phase 3: generating Frame 0 (character reference)")
    frame_0 = _generate_reference_frame(brief, clips)
    keyframes.append(frame_0)
    logger.info(
        "Phase 3: Frame 0 ready (%d b64 chars)", len(frame_0.image_b64)
    )
    if on_keyframe:
        on_keyframe(frame_0, total)

    # ── Frames 1..N: Expression transition frames ─────────────────────────
    for i, clip in enumerate(clips):
        frame_index = i + 1
        logger.info(
            "Phase 3: generating Frame %d (end of Clip %d: %s)",
            frame_index, clip.clip_number, clip.end_emotion[:60],
        )
        next_frame = _generate_transition_frame(
            prev_frame=keyframes[i],
            frame_index=frame_index,
            target_emotion=clip.end_emotion,
            brief=brief,
            clip=clip,
        )
        keyframes.append(next_frame)
        if on_keyframe:
            on_keyframe(next_frame, total)

    logger.info("Phase 3 complete — %d keyframes generated", len(keyframes))
    return keyframes


def regenerate_single_keyframe(
    frame_index: int,
    prev_keyframe: KeyFrame,
    target_emotion: str,
    brief: ProductionBrief,
    clip: Optional[ClipPrompt] = None,
    custom_prompt: Optional[str] = None,
) -> KeyFrame:
    """Regenerate one keyframe (called from /regen-image endpoint).

    Args:
        frame_index:    0 = regenerate the character reference via Imagen.
                        >0 = regenerate expression edit via Gemini Image.
        prev_keyframe:  The preceding keyframe (ignored when frame_index == 0).
        target_emotion: Desired end expression.
        brief:          ProductionBrief (character spec + background).
        clip:           Corresponding ClipPrompt (used for description label).
        custom_prompt:  Optional extra instructions from the user for this regen.

    Returns:
        New KeyFrame with updated image_b64.
    """
    if frame_index == 0:
        return _generate_reference_frame(brief, clips=[], custom_prompt=custom_prompt)

    if clip is None:
        raise ValueError(f"clip must be provided for frame_index={frame_index}")

    return _generate_transition_frame(
        prev_frame=prev_keyframe,
        frame_index=frame_index,
        target_emotion=target_emotion,
        brief=brief,
        clip=clip,
        custom_prompt=custom_prompt,
    )


# ---------------------------------------------------------------------------
# Frame 0 — Imagen 3 (with Gemini fallback)
# ---------------------------------------------------------------------------

def _generate_reference_frame(
    brief: ProductionBrief,
    clips: list[ClipPrompt],
    custom_prompt: Optional[str] = None,
) -> KeyFrame:
    """Generate Frame 0 — the initial character anchor image."""
    char = brief.character
    accessories_str = ", ".join(char.accessories) if char.accessories else "none"
    marks_str = ", ".join(char.distinguishing_marks) if char.distinguishing_marks else "none"

    # Use emotional state from brief.clips (ClipBrief), not ClipPrompt
    first_emotional_state = (
        brief.clips[0].emotional_state if brief.clips else "neutral, attentive"
    )

    # Build Imagen prompt from template
    prompt = IMAGEN_PROMPT_TEMPLATE.format(
        age=char.age,
        skin_tone=char.skin_tone,
        skin_hex=char.skin_hex,
        face_shape=char.face_shape,
        hair=char.hair,
        outfit=char.outfit,
        accessories_str=accessories_str,
        marks_str=marks_str,
        locked_background=brief.locked_background,
    )
    prompt += f"\n\nOpening expression: {first_emotional_state}."

    # Append user's custom feedback if provided
    if custom_prompt:
        prompt += f"\n\nUSER FEEDBACK FOR THIS REGEN: {custom_prompt}"

    image_b64: str | None = None

    # ── Attempt 1: Imagen 3 ───────────────────────────────────────────────
    try:
        image_bytes = imagen_client.generate_character_image(prompt)
        image_b64 = base64.b64encode(image_bytes).decode("utf-8")
        logger.info("Phase 3: Frame 0 generated via Imagen 3")
    except RuntimeError as exc:
        logger.warning(
            "Phase 3: Imagen 3 failed — '%s'. Trying Gemini Image fallback.", exc
        )

    # ── Attempt 2: Gemini Flash Image (text-to-image) ─────────────────────
    if image_b64 is None:
        image_b64 = gemini_image_client.generate_from_text(prompt)
        if image_b64:
            logger.info("Phase 3: Frame 0 generated via Gemini Image fallback")
        else:
            logger.error("Phase 3: Both Imagen 3 and Gemini Image fallback failed")

    # ── Hard fail if both attempts failed ─────────────────────────────────
    if image_b64 is None:
        raise RuntimeError(
            "Frame 0 generation failed: both Imagen 4 and Gemini Image returned no image.\n"
            "Check:\n"
            "  1. IMAGEN_MODEL in .env = 'imagen-4.0-generate-001' (no 'models/' prefix)\n"
            "  2. GEMINI_IMAGE_MODEL in .env = 'gemini-2.5-flash-image'\n"
            "  3. GOOGLE_API_KEY has access to both models\n"
            "  4. Prompt does not contain blocked terms (run with DEBUG logging to see sanitized prompt)"
        )

    return KeyFrame(
        index=0,
        image_b64=image_b64,
        mime_type="image/jpeg",
        description=f"Initial character reference — {first_emotional_state}",
        approved=False,
    )


# ---------------------------------------------------------------------------
# Frames 1..N — Gemini Flash Image expression edits
# ---------------------------------------------------------------------------

def _generate_transition_frame(
    prev_frame: KeyFrame,
    frame_index: int,
    target_emotion: str,
    brief: ProductionBrief,
    clip: ClipPrompt,
    custom_prompt: Optional[str] = None,
) -> KeyFrame:
    """Generate a transition frame by editing the previous frame's expression."""
    char = brief.character
    accessories_str = ", ".join(char.accessories) if char.accessories else "none"
    marks_str = ", ".join(char.distinguishing_marks) if char.distinguishing_marks else "none"

    custom_section = f"\n\nUSER FEEDBACK FOR THIS REGEN: {custom_prompt}" if custom_prompt else ""

    # Build the full instruction for the image edit
    instruction = (
        f"{SYSTEM_IMAGER}\n\n"
        f"TARGET EXPRESSION: {target_emotion}\n\n"
        f"KEEP IDENTICAL:\n"
        f"  Skin hex: {char.skin_hex}\n"
        f"  Hair: {char.hair}\n"
        f"  Outfit: {char.outfit}\n"
        f"  Accessories: {accessories_str}\n"
        f"  Distinguishing marks: {marks_str}\n"
        f"  Background: {brief.locked_background[:300]}\n"
        f"  Camera: TIGHT MCU chin to mid-chest, eye-level, static\n"
        f"  Output: 9:16 portrait, photorealistic, no text overlays"
        f"{custom_section}"
    )

    result_b64 = gemini_image_client.edit_expression(
        image_b64=prev_frame.image_b64,
        instruction=instruction,
    )

    if result_b64 is None:
        # Fallback: reuse previous frame — the cut is still seamless,
        # just the expression at that boundary won't change.
        logger.warning(
            "Phase 3: Gemini Image returned no image for Frame %d "
            "(Clip %d end-emotion: %s) — reusing previous frame as fallback",
            frame_index, clip.clip_number, target_emotion[:60],
        )
        result_b64 = prev_frame.image_b64

    return KeyFrame(
        index=frame_index,
        image_b64=result_b64,
        mime_type="image/jpeg",
        description=f"Clip {clip.clip_number} end-frame — {target_emotion[:80]}",
        approved=False,
    )