import logging
import re
from typing import Any

from ..models import ClipPrompt
from ..prompts.system_verifier import SYSTEM_VERIFIER
from .gemini_client import gemini_client

logger = logging.getLogger(__name__)

_EM_DASH_RE = re.compile(r"\s*—\s*")
_HYPHEN_RE = re.compile(r"\s+-\s+")


def verify_prompts(clips: list[ClipPrompt]) -> list[ClipPrompt]:
    """Run the 13-rule verifier on a set of clip prompts.

    Calls Gemini with SYSTEM_VERIFIER, receives a scored report with per-clip
    improved prompts, then applies the fixes back onto the ClipPrompt objects.
    Local auto-fixes (word count trim, dash removal) are always applied first
    so Gemini receives already-cleaner input.

    Args:
        clips: List of ClipPrompt objects generated by Phase 2.

    Returns:
        The same list with ``verified=True`` and any ``verification_issues``
        populated. Prompts are replaced with improved versions where issues
        were found.
    """
    # ---------------------------------------------------------------
    # Step 1 — fast local pre-fixes (no API call needed)
    # ---------------------------------------------------------------
    for clip in clips:
        clip.prompt = _remove_dashes(clip.prompt)
        clip.dialogue = _remove_dashes(clip.dialogue)

    # ---------------------------------------------------------------
    # Step 2 — build user message for Gemini verifier
    # ---------------------------------------------------------------
    import json

    clips_payload = [
        {
            "clip_number": c.clip_number,
            "duration_seconds": c.duration_seconds,
            "prompt": c.prompt,
            "dialogue": c.dialogue,
            "word_count": c.word_count,
            "end_emotion": c.end_emotion,
        }
        for c in clips
    ]
    user_message = (
        "Verify and fix the following clip prompts:\n\n"
        + json.dumps(clips_payload, ensure_ascii=False, indent=2)
    )

    # ---------------------------------------------------------------
    # Step 3 — call Gemini verifier
    # ---------------------------------------------------------------
    try:
        report: dict = gemini_client.generate_json(
            system_prompt=SYSTEM_VERIFIER,
            user_prompt=user_message,
            temperature=0.1,
        )
    except RuntimeError as exc:
        logger.error("Verifier Gemini call failed: %s — returning clips as-is", exc)
        for clip in clips:
            clip.verified = True
            clip.verification_issues = [f"Verifier unavailable: {exc}"]
        return clips

    # ---------------------------------------------------------------
    # Step 4 — apply report back to ClipPrompt objects
    # ---------------------------------------------------------------
    clip_map: dict[int, ClipPrompt] = {c.clip_number: c for c in clips}

    # SYSTEM_VERIFIER may return either:
    #  - a single clip object {"clip":..., "status":...}
    #  - a wrapper {"clips":[...], ...}
    #  - a bare list [...]
    # Normalize all shapes into a flat list of per-clip dicts.
    if isinstance(report, list):
        report_clips: list[dict] = report
    elif isinstance(report, dict):
        # Wrapper shape: {"clips": [...], "overall_score": ...}
        report_clips = report.get("clips", [])
        # Single-clip shape: {"clip": 1, "status": ..., ...}
        if not report_clips and "clip" in report:
            report_clips = [report]
    else:
        report_clips = []

    for entry in report_clips:
        clip_num = entry.get("clip")
        clip = clip_map.get(clip_num)
        if clip is None:
            logger.warning("Verifier returned result for unknown clip %s", clip_num)
            continue

        issues: list[str] = entry.get("issues", [])
        status: str = str(entry.get("status", "approved")).strip().lower()
        improved: str = entry.get("improved_prompt", "")

        clip.verification_issues = issues
        clip.verified = True

        # Backward/forward compatible status handling:
        # old: pass/fail, new: approved/improved
        should_apply = status in {"fail", "improved"}
        if should_apply and improved:
            # Apply the improved prompt from the verifier
            clip.prompt = _remove_dashes(improved)
            logger.info(
                "Clip %d: verifier applied fixes — %d issue(s)", clip_num, len(issues)
            )
        elif should_apply:
            logger.warning(
                "Clip %d: verifier flagged issues but returned no improved_prompt", clip_num
            )

    # Any clips not mentioned in the report get marked verified with no issues
    reported_clip_nums = {e.get("clip") for e in report_clips}
    for clip in clips:
        if clip.clip_number not in reported_clip_nums:
            clip.verified = True

    overall_score = report.get("overall_score", 100) if isinstance(report, dict) else 100
    needs_review = report.get("needs_human_review", False) if isinstance(report, dict) else False
    logger.info(
        "Verification complete — overall_score=%d needs_human_review=%s",
        overall_score,
        needs_review,
    )

    return clips


# ---------------------------------------------------------------------------
# Local auto-fix helpers (applied before and after Gemini call)
# ---------------------------------------------------------------------------

def _remove_dashes(text: str) -> str:
    """Replace em-dashes and surrounded hyphens with commas in text."""
    text = _EM_DASH_RE.sub(", ", text)
    text = _HYPHEN_RE.sub(" aur ", text)
    return text
